---
# Vault Configuration
vault_url: "https://vault.example.com"
vault_token: "{{ vault_token }}"
vault_path: "secret/kubernetes/certificates"

# Kubernetes Configuration
k8s_context: "default"
k8s_namespace: "default"
k8s_cert_path: "/etc/kubernetes/pki"

# Certificate Configuration
cert_expiry_threshold_days: 5
cert_types:
  - name: "apiserver"
    path: "apiserver.crt"
  - name: "apiserver-kubelet-client"
    path: "apiserver-kubelet-client.crt"
  - name: "front-proxy-client"
    path: "front-proxy-client.crt"
  - name: "etcd-server"
    path: "etcd/server.crt"
  - name: "etcd-healthcheck-client"
    path: "etcd/healthcheck-client.crt"

# Notification Configuration
notification_method: "both"  # Options: "slack", "email", or "both"
slack_webhook_url: "{{ slack_webhook_url }}"
notification_channel: "#certificate-alerts"
team_notification_channel: "#certificate-rotation"

# Email Configuration
email_recipients: "{{ email_recipients }}"
email_from: "cert-rotation@example.com"
smtp_host: "smtp.example.com"
smtp_port: 587
smtp_username: "{{ smtp_username }}"
smtp_password: "{{ smtp_password }}"
smtp_secure: "starttls"

# Splunk Configuration
splunk_url: "https://splunk.example.com"
splunk_username: "{{ splunk_username }}"
splunk_password: "{{ splunk_password }}"
splunk_search: "search index=certificates earliest=-1d | where expiry_days <= {{ cert_expiry_threshold_days }}" 