---
all:
  children:
    kubernetes_cluster:
      hosts:
        k8s_master:
          ansible_host: "{{ k8s_master_host }}"
          ansible_user: "{{ k8s_user }}"
          ansible_ssh_private_key_file: "{{ k8s_ssh_key }}"
        k8s_worker:
          ansible_host: "{{ k8s_worker_host }}"
          ansible_user: "{{ k8s_user }}"
          ansible_ssh_private_key_file: "{{ k8s_ssh_key }}"
      vars:
        ansible_python_interpreter: /usr/bin/python3 