---
- name: Monitor Kubernetes Certificates
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: slack_webhook_url
      prompt: "Enter Slack webhook URL"
      private: true
    - name: email_recipients
      prompt: "Enter email recipients (comma-separated)"
      private: false
    - name: smtp_username
      prompt: "Enter SMTP username"
      private: true
    - name: smtp_password
      prompt: "Enter SMTP password"
      private: true

  tasks:
    - name: Query Splunk for expiring certificates
      community.general.splunk_search:
        url: "{{ splunk_url }}"
        username: "{{ splunk_username }}"
        password: "{{ splunk_password }}"
        search: "{{ splunk_search }}"
      register: splunk_results

    - name: Process expiring certificates
      set_fact:
        expiring_certs: "{{ splunk_results.results | map(attribute='cert_name') | list }}"
      when: splunk_results.results | length > 0

    - name: Send Slack notification for expiring certificates
      include_tasks: ../roles/notification/tasks/slack.yml
      vars:
        message: "The following certificates will expire in {{ cert_expiry_threshold_days }} days: {{ expiring_certs | join(', ') }}"
        channel: "{{ notification_channel }}"
        color: "warning"
      when: 
        - expiring_certs | length > 0
        - notification_method in ["slack", "both"]

    - name: Send email notification for expiring certificates
      include_tasks: ../roles/notification/tasks/email.yml
      vars:
        message: "The following certificates will expire in {{ cert_expiry_threshold_days }} days:\n\n{{ expiring_certs | join('\n') }}"
        subject: "Certificate Expiration Alert - {{ cert_expiry_threshold_days }} days remaining"
      when: 
        - expiring_certs | length > 0
        - notification_method in ["email", "both"] 